version: "3"
services:
    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        container_name: zookeeper-kafka
        hostname: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "22181:2181"

    kafka:
        image: obsidiandynamics/kafka
        restart: "no"
        ports:
            - "2181:2181"
            - "9092:9092"
        environment:
            KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://${KAFKA_HOSTNAME}:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
            KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
            KAFKA_RESTART_ATTEMPTS: "10"
            KAFKA_RESTART_DELAY: "5"
            ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      
    ##############################
    # kafka-convergence-db
    # Base de données postgresql de kafka-convergence
    kafka-convergence-db:
        image: abesesr/postgres-fr_fr:15.1.0
        container_name: kafka-convergence-db
        restart: unless-stopped
        mem_limit: ${MEM_LIMIT}
        environment:
            # cf https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
            POSTGRES_DB: "kafka_convergence"
            POSTGRES_USER: ${KAFKA_CONVERGENCE_DB_POSTGRES_USER}
            POSTGRES_PASSWORD: ${KAFKA_CONVERGENCE_DB_POSTGRES_PASSWORD}
        volumes:
            - ./volumes/kafka-convergence-db/pgdata/:/var/lib/postgresql/data/
        labels:
            # pour envoyer les logs dans le puits de log de l'abes
            - "co.elastic.logs/enabled=true"
            - "co.elastic.logs/processors.add_fields.target="
            - "co.elastic.logs/processors.add_fields.fields.abes_appli=kafka-convergence"
            - "co.elastic.logs/processors.add_fields.fields.abes_middleware=postgresql"

    ##############################
    # kafdrop
    # IHM permettant de consulter les messages produits par Kafka via le port 9000
    kafdrop:
        image: obsidiandynamics/kafdrop
        restart: "no"
        ports:
            - "9000:9000"
        environment:
            KAFKA_BROKERCONNECT: "kafka:29092"
            JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
        depends_on:
            - "kafka"

    #################################
    # kafka-convergence-db-adminer
    # Interface d'admin de postgresql
    kafka-convergence-db-adminer:
        image: adminer:4.8.1
        container_name: kafka-convergence-db-adminer
        restart: unless-stopped
        mem_limit: ${MEM_LIMIT}
        ports:
            - ${KAFKA_CONVERGENCE_DB_ADMINER_HTTP_PORT}:8080
        depends_on:
            - kafka-convergence-db
        environment:
            ADMINER_DEFAULT_SERVER: "kafka-convergence-db"
        logging:
            driver: none # pas de log pour adminer pour ne pas polluer